- (BOOL) shouldAddItemToHistory:(id)anItem;
- (BOOL) shouldReturnItemFromHistory:(id)anItem;
- (BOOL) shouldSetLastResult:(NSString *)aString;
- (BOOL) shouldAppendPartialResult:(NSString *)string;
- (BOOL) shouldSetScript:(NSString *)aScript;
- (BOOL) shouldSetOptions:(NSDictionary *)opts;