/*
 * Generated by dtrace(1M).
 */

#ifndef	_BMSCRIPTPROBES_H
#define	_BMSCRIPTPROBES_H

#include <unistd.h>

#ifdef	__cplusplus
extern "C" {
#endif

#define BMSCRIPT_STABILITY "___dtrace_stability$BMScript$v1$1_1_0_1_1_0_1_1_0_1_1_0_1_1_0"

#define BMSCRIPT_TYPEDEFS "___dtrace_typedefs$BMScript$v2"

#define	BMSCRIPT_ACQUIRE_LOCK_END(arg0) \
do { \
	__asm__ volatile(".reference " BMSCRIPT_TYPEDEFS); \
	__dtrace_probe$BMScript$acquire_lock_end$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " BMSCRIPT_STABILITY); \
} while (0)
#define	BMSCRIPT_ACQUIRE_LOCK_END_ENABLED() \
	__dtrace_isenabled$BMScript$acquire_lock_end$v1()
#define	BMSCRIPT_ACQUIRE_LOCK_START(arg0) \
do { \
	__asm__ volatile(".reference " BMSCRIPT_TYPEDEFS); \
	__dtrace_probe$BMScript$acquire_lock_start$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " BMSCRIPT_STABILITY); \
} while (0)
#define	BMSCRIPT_ACQUIRE_LOCK_START_ENABLED() \
	__dtrace_isenabled$BMScript$acquire_lock_start$v1()
#define	BMSCRIPT_END_NET_EXECUTE(arg0) \
do { \
	__asm__ volatile(".reference " BMSCRIPT_TYPEDEFS); \
	__dtrace_probe$BMScript$end_net_execute$v1$63686172202a(arg0); \
	__asm__ volatile(".reference " BMSCRIPT_STABILITY); \
} while (0)
#define	BMSCRIPT_END_NET_EXECUTE_ENABLED() \
	__dtrace_isenabled$BMScript$end_net_execute$v1()
#define	BMSCRIPT_START_NET_EXECUTE(arg0, arg1, arg2) \
do { \
	__asm__ volatile(".reference " BMSCRIPT_TYPEDEFS); \
	__dtrace_probe$BMScript$start_net_execute$v1$63686172202a$63686172202a$63686172202a(arg0, arg1, arg2); \
	__asm__ volatile(".reference " BMSCRIPT_STABILITY); \
} while (0)
#define	BMSCRIPT_START_NET_EXECUTE_ENABLED() \
	__dtrace_isenabled$BMScript$start_net_execute$v1()


extern void __dtrace_probe$BMScript$acquire_lock_end$v1$63686172202a(char *);
extern int __dtrace_isenabled$BMScript$acquire_lock_end$v1(void);
extern void __dtrace_probe$BMScript$acquire_lock_start$v1$63686172202a(char *);
extern int __dtrace_isenabled$BMScript$acquire_lock_start$v1(void);
extern void __dtrace_probe$BMScript$end_net_execute$v1$63686172202a(char *);
extern int __dtrace_isenabled$BMScript$end_net_execute$v1(void);
extern void __dtrace_probe$BMScript$start_net_execute$v1$63686172202a$63686172202a$63686172202a(char *, char *, char *);
extern int __dtrace_isenabled$BMScript$start_net_execute$v1(void);

#ifdef	__cplusplus
}
#endif

#endif	/* _BMSCRIPTPROBES_H */
