- (id) initWithScriptSource:(NSString *)scriptSource;
- (id) initWithScriptSource:(NSString *)scriptSource options:(NSDictionary *)scriptOptions;     /* designated initializer */
// ...

+ (id) scriptWithSource:(NSString *)scriptSource options:(NSDictionary *)scriptOptions;
// ...