- (NSString *) scriptSourceFromHistoryAtIndex:(NSUInteger)index;
- (NSData *) resultFromHistoryAtIndex:(NSUInteger)index;
- (NSString *) lastScriptSourceFromHistory;
- (NSData *) lastResultFromHistory;